"""Generate process-quality monitoring reports from prediction CSV files."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.monitoring import group_risk_summary, overall_risk_summary, top_risk_predictions


def parse_group_columns(value: str | None) -> list[str]:
    """Parse optional comma-separated group columns."""
    if value is None or not value.strip():
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate monitoring reports from prediction outputs.")
    parser.add_argument(
        "--predictions-path",
        type=Path,
        required=True,
        help="Prediction CSV file generated by predict_with_model.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/reports/monitoring"),
        help="Directory where monitoring reports will be written.",
    )
    parser.add_argument(
        "--group-columns",
        type=parse_group_columns,
        default=[],
        help="Optional comma-separated columns for grouped risk reports.",
    )
    parser.add_argument(
        "--high-risk-threshold",
        type=float,
        default=0.5,
        help="Fail probability threshold for high-risk rows.",
    )
    parser.add_argument(
        "--alert-ratio-threshold",
        type=float,
        default=0.25,
        help="Group high-risk ratio threshold for alert flags.",
    )
    parser.add_argument("--top-n", type=int, default=20, help="Number of top-risk rows to export.")
    return parser.parse_args()


def generate_monitoring_reports(
    predictions_path: Path,
    output_dir: Path,
    group_columns: list[str] | None = None,
    high_risk_threshold: float = 0.5,
    alert_ratio_threshold: float = 0.25,
    top_n: int = 20,
) -> dict[str, Path]:
    """Generate monitoring report CSV files and return their paths."""
    if not predictions_path.exists():
        raise FileNotFoundError(f"Prediction CSV not found: {predictions_path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    predictions = pd.read_csv(predictions_path)

    overall_path = output_dir / "overall_risk_summary.csv"
    top_risk_path = output_dir / "top_risk_predictions.csv"
    group_path = output_dir / "group_risk_summary.csv"

    overall = overall_risk_summary(predictions, high_risk_threshold=high_risk_threshold)
    overall.to_frame().reset_index().rename(columns={"index": "metric"}).to_csv(overall_path, index=False)

    top_risk_predictions(predictions, top_n=top_n).to_csv(top_risk_path, index=False)

    paths = {
        "overall": overall_path,
        "top_risk": top_risk_path,
    }

    group_columns = group_columns or []
    if group_columns:
        group_risk_summary(
            predictions,
            group_cols=group_columns,
            high_risk_threshold=high_risk_threshold,
            alert_ratio_threshold=alert_ratio_threshold,
        ).to_csv(group_path, index=False)
        paths["group"] = group_path

    return paths


def main() -> int:
    args = parse_args()
    paths = generate_monitoring_reports(
        predictions_path=args.predictions_path,
        output_dir=args.output_dir,
        group_columns=args.group_columns,
        high_risk_threshold=args.high_risk_threshold,
        alert_ratio_threshold=args.alert_ratio_threshold,
        top_n=args.top_n,
    )
    for name, path in paths.items():
        print(f"{name} report written to: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
