"""Markdown reporting utilities for SECOM analytics outputs."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def dataframe_to_markdown(df: pd.DataFrame, max_rows: int = 20) -> str:
    """Render a DataFrame as a simple GitHub-compatible Markdown table."""
    if df.empty:
        return "_No rows._"

    display_df = df.head(max_rows).copy()
    headers = [str(column) for column in display_df.columns]
    rows = [[str(value) for value in row] for row in display_df.to_numpy()]

    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def read_csv_if_exists(path: Path) -> pd.DataFrame | None:
    """Read a CSV file only when it exists."""
    path = Path(path)
    if not path.exists():
        return None
    return pd.read_csv(path)


def add_table_section(
    sections: list[str],
    title: str,
    csv_path: Path,
    max_rows: int = 20,
) -> None:
    """Append a Markdown section for a CSV table when the file exists."""
    df = read_csv_if_exists(csv_path)
    if df is None:
        return
    sections.append(f"## {title}\n\nSource: `{csv_path}`\n\n{dataframe_to_markdown(df, max_rows=max_rows)}")


def build_summary_report(
    reports_dir: Path = Path("outputs/reports"),
    monitoring_dir: Path = Path("outputs/reports/monitoring"),
    output_path: Path = Path("outputs/reports/summary_report.md"),
) -> str:
    """Build a Markdown summary report from generated CSV report files."""
    reports_dir = Path(reports_dir)
    monitoring_dir = Path(monitoring_dir)

    sections = [
        "# SECOM Manufacturing Analytics Summary",
        (
            "This report summarizes available data quality, feature assembly, "
            "prediction monitoring, and risk outputs generated by the pipeline."
        ),
    ]

    add_table_section(sections, "Data Overview", reports_dir / "quality" / "overview.csv")
    add_table_section(sections, "Class Distribution", reports_dir / "quality" / "class_distribution.csv")
    add_table_section(sections, "Top Missing Features", reports_dir / "quality" / "missingness.csv", max_rows=20)
    add_table_section(sections, "Feature Join Report", reports_dir / "feature_join_report.csv")
    add_table_section(sections, "Feature Missingness Report", reports_dir / "feature_missingness_report.csv", max_rows=20)
    add_table_section(sections, "Overall Risk Summary", monitoring_dir / "overall_risk_summary.csv")
    add_table_section(sections, "Group Risk Summary", monitoring_dir / "group_risk_summary.csv", max_rows=20)
    add_table_section(sections, "Top Risk Predictions", monitoring_dir / "top_risk_predictions.csv", max_rows=20)

    report = "\n\n".join(sections) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    return report
